name: Changesets PR or Publish

on:
  push:
    branches: [main, beta]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Update npm
        run: npm install -g npm@11.5.1

      - name: Build Package
        run: yarn workspace overlay-kit run build

      - name: Create Changesets Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          version: yarn changeset:version
          publish: yarn changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
